const placeholderTherapists = [
  {
    id: 1,
    slug: "therapist-1",
    name: "Therapist 1",
    profession: "Integrative Psychotherapist",
    online_or_in_person: "In Person",
    address: "London, SE1",
    specialisms: ["Anxiety", "ADHD", "Stress"],
    email: "therapist1@example.com",
    phone_number: "07123456789",
    fee_per_hour: 55,
    therapy_types_offered: ["CBT", "Person-Centred Therapy"],
    website_link: "https://www.therapist1.com",
    profile_image: "therapist1.jpg",
    qualifications_and_accreditations: [
      "MBACP - Accredited by the British Association of Counselling & Psychotherapy",
      "Certificate in Cognitive Behavioural Therapy",
    ],
    age: 35,
    faith: "Christian",
    insurance: ["Bupa", "Aviva"],
    languages: ["English", "French"],
    sexuality: "Heterosexual",
    ethnicity: ["White British"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 2,
    slug: "therapist-2",
    name: "Therapist 2",
    profession: "CBT Therapist",
    online_or_in_person: "Online & In Person",
    address: "Manchester, M1",
    specialisms: ["Depression", "Anxiety", "Relationship problems"],
    email: "therapist2@example.com",
    phone_number: "07234567890",
    fee_per_hour: 70,
    therapy_types_offered: ["CBT", "Gestalt Therapy"],
    website_link: "https://www.therapist2.com",
    profile_image: "therapist2.jpg",
    qualifications_and_accreditations: [
      "Advanced Diploma in Cognitive Behavioural Therapy",
      "Accredited by the UK Council for Psychotherapy (UKCP)",
    ],
    age: 40,
    faith: "Agnostic",
    insurance: ["Cigna", "Vitality"],
    languages: ["English", "Spanish"],
    sexuality: "Bisexual",
    ethnicity: ["British Asian"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 3,
    slug: "therapist-3",
    name: "Therapist 3",
    profession: "Psychodynamic Counsellor",
    online_or_in_person: "In Person",
    address: "Birmingham, B1",
    specialisms: ["Trauma", "Abuse", "Anxiety"],
    email: "therapist3@example.com",
    phone_number: "07345678901",
    fee_per_hour: 65,
    therapy_types_offered: ["Psychodynamic Therapy", "CBT"],
    website_link: "https://www.therapist3.com",
    profile_image: "therapist3.jpg",
    qualifications_and_accreditations: [
      "Diploma in Psychodynamic Counselling",
      "Member of the British Association for Counselling & Psychotherapy (MBACP)",
    ],
    age: 50,
    faith: "Buddhist",
    insurance: ["Bupa"],
    languages: ["English", "Mandarin"],
    sexuality: "Heterosexual",
    ethnicity: ["Chinese"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 4,
    slug: "therapist-4",
    name: "Therapist 4",
    profession: "Integrative Therapist",
    online_or_in_person: "Online",
    address: null,
    specialisms: ["Stress", "Burnout", "Career counselling"],
    email: "therapist4@example.com",
    phone_number: "07456789012",
    fee_per_hour: 60,
    therapy_types_offered: ["Integrative Therapy", "Mindfulness-Based Therapy"],
    website_link: "https://www.therapist4.com",
    profile_image: "therapist4.jpg",
    qualifications_and_accreditations: [
      "Certificate in Integrative Counselling",
      "Accredited Member of the British Association for Counselling & Psychotherapy (MBACP)",
    ],
    age: 37,
    faith: "Atheist",
    insurance: ["Healix"],
    languages: ["English", "German"],
    sexuality: "LGBTQ+",
    ethnicity: ["White British"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 5,
    slug: "therapist-5",
    name: "Therapist 5",
    profession: "Trauma Specialist",
    online_or_in_person: "In Person",
    address: "Leeds, LS1",
    specialisms: ["Trauma", "PTSD"],
    email: "therapist5@example.com",
    phone_number: "07567890123",
    fee_per_hour: 85,
    therapy_types_offered: ["CBT", "Somatic Therapy"],
    website_link: "https://www.therapist5.com",
    profile_image: "therapist5.jpg",
    qualifications_and_accreditations: [
      "Certified Trauma Specialist - EMDR UK",
      "Diploma in Somatic Therapy",
    ],
    age: 42,
    faith: "Christian",
    insurance: ["Vitality"],
    languages: ["English", "French"],
    sexuality: "Heterosexual",
    ethnicity: ["Black British"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 6,
    slug: "therapist-6",
    name: "Therapist 6",
    profession: "Child Psychotherapist",
    online_or_in_person: "Online & In Person",
    address: "Edinburgh, EH1",
    specialisms: ["Child counselling", "Anxiety", "Attachment disorder"],
    email: "therapist6@example.com",
    phone_number: "07678901234",
    fee_per_hour: 70,
    therapy_types_offered: ["Play Therapy", "CBT"],
    website_link: "https://www.therapist6.com",
    profile_image: "therapist6.jpg",
    qualifications_and_accreditations: [
      "Accredited by the Association of Child Psychotherapists (ACP)",
      "Diploma in Child Psychotherapy",
    ],
    age: 38,
    faith: "Agnostic",
    insurance: ["Aviva", "Healix"],
    languages: ["English", "Spanish"],
    sexuality: "Heterosexual",
    ethnicity: ["White British", "Scottish"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 7,
    slug: "therapist-7",
    name: "Therapist 7",
    profession: "Existential Therapist",
    online_or_in_person: "In Person",
    address: "Bristol, BS1",
    specialisms: ["Existential issues", "Depression", "Loneliness"],
    email: "therapist7@example.com",
    phone_number: "07789012345",
    fee_per_hour: 75,
    therapy_types_offered: ["Existential Therapy", "Mindfulness-Based Therapy"],
    website_link: "https://www.therapist7.com",
    profile_image: "therapist7.jpg",
    qualifications_and_accreditations: [
      "Certificate in Existential Psychotherapy",
      "Member of the British Psychological Society (BPS)",
    ],
    age: 45,
    faith: "Christian",
    insurance: ["Bupa", "Vitality"],
    languages: ["English", "Italian"],
    sexuality: null,
    ethnicity: ["Italian", "White British"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 8,
    slug: "therapist-8",
    name: "Therapist 8",
    profession: "Gestalt Therapist",
    online_or_in_person: "Online",
    address: null,
    specialisms: ["Relationship problems", "Trauma", "Burnout"],
    email: "therapist8@example.com",
    phone_number: "07890123456",
    fee_per_hour: 80,
    therapy_types_offered: ["Gestalt Therapy", "Integrative Therapy"],
    website_link: "https://www.therapist8.com",
    profile_image: "therapist8.jpg",
    qualifications_and_accreditations: [
      "Certified Gestalt Therapist - Gestalt Centre London",
      "Diploma in Integrative Counselling",
    ],
    age: 50,
    faith: "Buddhist",
    insurance: ["Cigna"],
    languages: ["English", "Mandarin"],
    sexuality: "Bisexual",
    ethnicity: ["Chinese"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 9,
    slug: "therapist-9",
    name: "Therapist 9",
    profession: "Trauma Specialist",
    online_or_in_person: "In Person",
    address: "Glasgow, G1",
    specialisms: ["Trauma", "PTSD", "Abuse"],
    email: "therapist9@example.com",
    phone_number: "07901234567",
    fee_per_hour: 90,
    therapy_types_offered: ["Trauma-Focused CBT", "EMDR"],
    website_link: "https://www.therapist9.com",
    profile_image: "therapist9.jpg",
    qualifications_and_accreditations: [
      "Certified Trauma Specialist - EMDR Association UK",
      "Diploma in Trauma Counselling",
    ],
    age: 47,
    faith: "Christian",
    insurance: ["Bupa"],
    languages: ["English", "Welsh"],
    sexuality: "LGBTQ+",
    ethnicity: ["Black British"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 10,
    slug: "therapist-10",
    name: "Therapist 10",
    profession: "Addiction Counsellor",
    online_or_in_person: "Online",
    address: null,
    specialisms: ["Addiction", "Alcoholism", "Drug addiction"],
    email: "therapist10@example.com",
    phone_number: "07012345678",
    fee_per_hour: 65,
    therapy_types_offered: ["CBT", "Person-Centred Therapy"],
    website_link: "https://www.therapist10.com",
    profile_image: "therapist10.jpg",
    qualifications_and_accreditations: [
      "Certificate in Addiction Counselling",
      "MBACP - Accredited by the British Association of Counselling & Psychotherapy",
    ],
    age: 39,
    faith: "Agnostic",
    insurance: ["Vitality"],
    languages: ["English"],
    sexuality: "Heterosexual",
    ethnicity: ["White British"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 11,
    slug: "therapist-11",
    name: "Therapist 11",
    profession: "CBT Practitioner",
    online_or_in_person: "Online & In Person",
    address: "London, SW1",
    specialisms: ["Anxiety", "Depression", "Panic attacks"],
    email: "therapist11@example.com",
    phone_number: "07112233445",
    fee_per_hour: 85,
    therapy_types_offered: ["CBT", "Schema Therapy"],
    website_link: "https://www.therapist11.com",
    profile_image: "therapist11.jpg",
    qualifications_and_accreditations: [
      "BABCP Accredited - British Association for Behavioural and Cognitive Psychotherapies",
      "Advanced Diploma in CBT",
    ],
    age: 40,
    faith: "Atheist",
    insurance: ["Bupa", "Aviva"],
    languages: ["English", "French"],
    sexuality: null,
    ethnicity: ["White British"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 12,
    slug: "therapist-12",
    name: "Therapist 12",
    profession: "Psychodynamic Counsellor",
    online_or_in_person: "In Person",
    address: "Manchester, M1",
    specialisms: ["Relationship problems", "Self-esteem", "Trauma"],
    email: "therapist12@example.com",
    phone_number: "07222334455",
    fee_per_hour: 70,
    therapy_types_offered: ["Psychodynamic Therapy", "CBT"],
    website_link: "https://www.therapist12.com",
    profile_image: "therapist12.jpg",
    qualifications_and_accreditations: [
      "Accredited Member of the British Association for Counselling and Psychotherapy (BACP)",
      "Certificate in Psychodynamic Counselling",
    ],
    age: 35,
    faith: "Christian",
    insurance: ["Vitality"],
    languages: ["English", "Spanish"],
    sexuality: "Heterosexual",
    ethnicity: ["White British"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 13,
    slug: "therapist-13",
    name: "Therapist 13",
    profession: "Art Psychotherapist",
    online_or_in_person: "Online",
    address: null,
    specialisms: ["Autism", "ADHD", "Child counselling"],
    email: "therapist13@example.com",
    phone_number: "07333445566",
    fee_per_hour: 60,
    therapy_types_offered: ["Art Therapy", "Integrative Therapy"],
    website_link: "https://www.therapist13.com",
    profile_image: "therapist13.jpg",
    qualifications_and_accreditations: [
      "HCPC Registered Art Psychotherapist",
      "MA in Art Psychotherapy",
    ],
    age: 32,
    faith: "Agnostic",
    insurance: ["Aviva"],
    languages: ["English"],
    sexuality: "Bisexual",
    ethnicity: ["Black British"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 14,
    slug: "therapist-14",
    name: "Therapist 14",
    profession: "Integrative Counsellor",
    online_or_in_person: "In Person",
    address: "Liverpool, L1",
    specialisms: ["Stress", "Burnout", "Work-related stress"],
    email: "therapist14@example.com",
    phone_number: "07444556677",
    fee_per_hour: 75,
    therapy_types_offered: ["Integrative Therapy", "CBT"],
    website_link: "https://www.therapist14.com",
    profile_image: "therapist14.jpg",
    qualifications_and_accreditations: [
      "MBACP - Accredited by the British Association for Counselling & Psychotherapy",
      "Diploma in Integrative Counselling",
    ],
    age: 41,
    faith: "Buddhist",
    insurance: ["Cigna"],
    languages: ["English", "German"],
    sexuality: null,
    ethnicity: ["Asian British"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 15,
    slug: "therapist-15",
    name: "Therapist 15",
    profession: "Family Therapist",
    online_or_in_person: "Online & In Person",
    address: "Leeds, LS1",
    specialisms: ["Family issues", "Child counselling", "Trauma"],
    email: "therapist15@example.com",
    phone_number: "07555667788",
    fee_per_hour: 90,
    therapy_types_offered: ["Family Therapy", "Emotionally Focused Therapy"],
    website_link: "https://www.therapist15.com",
    profile_image: "therapist15.jpg",
    qualifications_and_accreditations: [
      "UKCP Accredited Family Therapist",
      "Certificate in Emotionally Focused Therapy",
    ],
    age: 50,
    faith: "Christian",
    insurance: ["Healix", "Bupa"],
    languages: ["English", "Hindi"],
    sexuality: "LGBTQ+",
    ethnicity: ["Indian", "British Asian"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 16,
    slug: "therapist-16",
    name: "Therapist 16",
    profession: "Gestalt Therapist",
    online_or_in_person: "In Person",
    address: "Birmingham, B1",
    specialisms: ["Anxiety", "Depression", "Self-esteem"],
    email: "therapist16@example.com",
    phone_number: "07666778899",
    fee_per_hour: 80,
    therapy_types_offered: ["Gestalt Therapy", "Integrative Therapy"],
    website_link: "https://www.therapist16.com",
    profile_image: "therapist16.jpg",
    qualifications_and_accreditations: [
      "Certified Gestalt Therapist - Gestalt Centre London",
      "Diploma in Integrative Counselling",
    ],
    age: 45,
    faith: "Christian",
    insurance: ["Bupa", "Aviva"],
    languages: ["English", "Punjabi"],
    sexuality: "Heterosexual",
    ethnicity: ["White British", "Indian"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 17,
    slug: "therapist-17",
    name: "Therapist 17",
    profession: "Trauma Counsellor",
    online_or_in_person: "Online",
    address: null,
    specialisms: ["Trauma", "PTSD", "Abuse"],
    email: "therapist17@example.com",
    phone_number: "07777889900",
    fee_per_hour: 85,
    therapy_types_offered: ["Trauma-Focused CBT", "Somatic Therapy"],
    website_link: "https://www.therapist17.com",
    profile_image: "therapist17.jpg",
    qualifications_and_accreditations: [
      "Certified Trauma Specialist - EMDR Association UK",
      "Certificate in Somatic Trauma Therapy",
    ],
    age: 40,
    faith: "Agnostic",
    insurance: ["Aviva"],
    languages: ["English", "French"],
    sexuality: "Bisexual",
    ethnicity: ["White British"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 18,
    slug: "therapist-18",
    name: "Therapist 18",
    profession: "Psychodynamic Psychotherapist",
    online_or_in_person: "In Person",
    address: "Brighton, BN1",
    specialisms: ["Relationship problems", "Anxiety", "Trauma"],
    email: "therapist18@example.com",
    phone_number: "07888990011",
    fee_per_hour: 90,
    therapy_types_offered: ["Psychodynamic Therapy", "CBT"],
    website_link: "https://www.therapist18.com",
    profile_image: "therapist18.jpg",
    qualifications_and_accreditations: [
      "UKCP Accredited",
      "Certificate in Psychodynamic Psychotherapy",
    ],
    age: 38,
    faith: "Buddhist",
    insurance: ["Healix", "Cigna"],
    languages: ["English", "Spanish"],
    sexuality: null,
    ethnicity: ["White British"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 19,
    slug: "therapist-19",
    name: "Therapist 19",
    profession: "Child Psychotherapist",
    online_or_in_person: "Online & In Person",
    address: "Edinburgh, EH1",
    specialisms: ["Child counselling", "Behaviour problems", "ADHD"],
    email: "therapist19@example.com",
    phone_number: "07999001122",
    fee_per_hour: 65,
    therapy_types_offered: ["Play Therapy", "CBT"],
    website_link: "https://www.therapist19.com",
    profile_image: "therapist19.jpg",
    qualifications_and_accreditations: [
      "Accredited by the Association of Child Psychotherapists (ACP)",
      "Diploma in Play Therapy",
    ],
    age: 34,
    faith: "Atheist",
    insurance: ["Vitality"],
    languages: ["English"],
    sexuality: "Heterosexual",
    ethnicity: ["Black British"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
  {
    id: 20,
    slug: "therapist-20",
    name: "Therapist 20",
    profession: "Existential Psychotherapist",
    online_or_in_person: "Online",
    address: null,
    specialisms: ["Existential issues", "Anxiety", "Self-esteem"],
    email: "therapist20@example.com",
    phone_number: "07111223344",
    fee_per_hour: 95,
    therapy_types_offered: ["Existential Therapy", "CBT"],
    website_link: "https://www.therapist20.com",
    profile_image: "therapist20.jpg",
    qualifications_and_accreditations: [
      "UKCP Accredited",
      "Certificate in Existential Psychotherapy",
    ],
    age: 48,
    faith: "Agnostic",
    insurance: ["Bupa"],
    languages: ["English", "Italian"],
    sexuality: "LGBTQ+",
    ethnicity: ["White British", "Italian"],
    biography:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis purus vel sapien dignissim, a posuere lectus dapibus. Nullam malesuada leo eu nunc sagittis, sed ultrices sapien vulputate. Phasellus pharetra metus et elit sollicitudin interdum. Donec in orci quis turpis faucibus mollis in non ligula. Integer malesuada odio vel erat facilisis, quis tincidunt ex feugiat. In accumsan felis nec erat commodo tincidunt. Suspendisse potenti. Etiam gravida vehicula turpis, nec bibendum sem condimentum sed. Curabitur viverra, sapien sit amet tincidunt ultricies, elit felis malesuada libero, non ultrices justo elit vel magna.",
    how_we_start:
      "I offer a free 15-minute consultations where we can meet and chat about your needs, expectations and desires for therapy. If we think we’re a good fit, we meet at the same time each week for 50 minute sessions. I work in pre-paid blocks of four sessions, paid upfront before the start of each block.",
  },
];

export default placeholderTherapists;
