const placeholderLanguages = [
  { label: "English", id: "English" },
  { label: "Spanish", id: "Spanish" },
  { label: "French", id: "French" },
  { label: "German", id: "German" },
  { label: "Mandarin", id: "Mandarin" },
  { label: "Cantonese", id: "Cantonese" },
  { label: "Hindi", id: "Hindi" },
  { label: "Bengali", id: "Bengali" },
  { label: "Punjabi", id: "Punjabi" },
  { label: "Urdu", id: "Urdu" },
  { label: "Portuguese", id: "Portuguese" },
  { label: "Arabic", id: "Arabic" },
  { label: "Russian", id: "Russian" },
  { label: "Italian", id: "Italian" },
  { label: "Japanese", id: "Japanese" },
  { label: "Korean", id: "Korean" },
  { label: "Swedish", id: "Swedish" },
  { label: "Dutch", id: "Dutch" },
  { label: "Turkish", id: "Turkish" },
  { label: "Polish", id: "Polish" },
  { label: "Tamil", id: "Tamil" },
  { label: "Gujarati", id: "Gujarati" },
  { label: "Malay", id: "Malay" },
  { label: "Greek", id: "Greek" },
  { label: "Vietnamese", id: "Vietnamese" },
  { label: "Thai", id: "Thai" },
  { label: "Farsi", id: "Farsi" },
  { label: "Hebrew", id: "Hebrew" },
  { label: "Swahili", id: "Swahili" },
  { label: "Zulu", id: "Zulu" },
  { label: "Afrikaans", id: "Afrikaans" },
  { label: "Norwegian", id: "Norwegian" },
  { label: "Danish", id: "Danish" },
  { label: "Finnish", id: "Finnish" },
  { label: "Hungarian", id: "Hungarian" },
  { label: "Czech", id: "Czech" },
  { label: "Slovak", id: "Slovak" },
  { label: "Romanian", id: "Romanian" },
  { label: "Bulgarian", id: "Bulgarian" },
  { label: "Serbian", id: "Serbian" },
  { label: "Croatian", id: "Croatian" },
  { label: "Bosnian", id: "Bosnian" },
  { label: "Albanian", id: "Albanian" },
  { label: "Ukrainian", id: "Ukrainian" },
  { label: "Latvian", id: "Latvian" },
  { label: "Lithuanian", id: "Lithuanian" },
  { label: "Estonian", id: "Estonian" },
  { label: "Welsh", id: "Welsh" },
  { label: "Irish", id: "Irish" },
  { label: "Scottish Gaelic", id: "Scottish Gaelic" },
];

export default placeholderLanguages;
