const placeholderOptions = [
  { label: "Abortion", id: "Abortion" },
  { label: "Abuse", id: "Abuse" },
  { label: "Addiction", id: "Addiction" },
  { label: "ADHD", id: "ADHD" },
  {
    label: "Adoption counselling for adults",
    id: "Adoption counselling for adults",
  },
  { label: "Affairs and betrayals", id: "Affairs and betrayals" },
  { label: "Alcoholism", id: "Alcoholism" },
  { label: "Anger management", id: "Anger management" },
  { label: "Anorexia nervosa", id: "Anorexia nervosa" },
  {
    label: "Antisocial personality disorder",
    id: "Antisocial personality disorder",
  },
  { label: "Anxiety", id: "Anxiety" },
  { label: "ARFID", id: "ARFID" },
  { label: "Attachment disorder", id: "Attachment disorder" },
  {
    label: "Attachment disorder in children",
    id: "Attachment disorder in children",
  },
  { label: "Autism", id: "Autism" },
  {
    label: "Avoidant personality disorder",
    id: "Avoidant personality disorder",
  },
  { label: "Baby loss", id: "Baby loss" },
  { label: "Behaviour problems", id: "Behaviour problems" },
  { label: "Bereavement", id: "Bereavement" },
  { label: "Binge-eating disorder", id: "Binge-eating disorder" },
  { label: "Bipolar disorder", id: "Bipolar disorder" },
  { label: "Blended family", id: "Blended family" },
  { label: "Boarding school syndrome", id: "Boarding school syndrome" },
  {
    label: "Body dysmorphic disorder (BDD)",
    id: "Body dysmorphic disorder (BDD)",
  },
  {
    label: "Borderline personality disorder (BPD)",
    id: "Borderline personality disorder (BPD)",
  },
  { label: "Bulimia nervosa", id: "Bulimia nervosa" },
  { label: "Bullying", id: "Bullying" },
  { label: "Burnout", id: "Burnout" },
  { label: "Cancer", id: "Cancer" },
  { label: "Career counselling", id: "Career counselling" },
  { label: "Carer support", id: "Carer support" },
  { label: "Child counselling", id: "Child counselling" },
  { label: "Childhood bereavement", id: "Childhood bereavement" },
  { label: "Childhood bullying", id: "Childhood bullying" },
  { label: "Childless not by choice", id: "Childless not by choice" },
  {
    label: "Children’s learning difficulties",
    id: "Children’s learning difficulties",
  },
  {
    label: "Chronic fatigue syndrome/ME",
    id: "Chronic fatigue syndrome/ME",
  },
  { label: "Chronic illness", id: "Chronic illness" },
  { label: "Climate and eco-anxiety", id: "Climate and eco-anxiety" },
  { label: "Dementia", id: "Dementia" },
  {
    label: "Dependent personality disorder",
    id: "Dependent personality disorder",
  },
  { label: "Depression", id: "Depression" },
  {
    label: "Depression and anxiety in children",
    id: "Depression and anxiety in children",
  },
  { label: "Disabilities", id: "Disabilities" },
  { label: "Discrimination", id: "Discrimination" },
  { label: "Dissociation", id: "Dissociation" },
  { label: "Domestic abuse", id: "Domestic abuse" },
  { label: "Drug addiction", id: "Drug addiction" },
  { label: "Dyslexia", id: "Dyslexia" },
  { label: "Dyspraxia", id: "Dyspraxia" },
  { label: "Eating disorders", id: "Eating disorders" },
  { label: "Emotional abuse", id: "Emotional abuse" },
  { label: "Family issues", id: "Family issues" },
  { label: "Gambling", id: "Gambling" },
  { label: "Gender dysphoria", id: "Gender dysphoria" },
  {
    label: "Generalised anxiety disorder (GAD)",
    id: "Generalised anxiety disorder (GAD)",
  },
  { label: "Health anxiety", id: "Health anxiety" },
  { label: "Hearing voices", id: "Hearing voices" },
  { label: "High sensitivity", id: "High sensitivity" },
  {
    label: "Histrionic personality disorder",
    id: "Histrionic personality disorder",
  },
  { label: "HIV/AIDS", id: "HIV/AIDS" },
  { label: "Hoarding", id: "Hoarding" },
  { label: "Infertility", id: "Infertility" },
  { label: "Internet addiction", id: "Internet addiction" },
  { label: "Jealousy", id: "Jealousy" },
  { label: "Kink-aware therapy", id: "Kink-aware therapy" },
  { label: "Learning difficulties", id: "Learning difficulties" },
  { label: "Learning disabilities", id: "Learning disabilities" },
  { label: "LGBTQ+ counselling", id: "LGBTQ+ counselling" },
  { label: "Loneliness", id: "Loneliness" },
  { label: "Low self-confidence", id: "Low self-confidence" },
  { label: "Low self-esteem", id: "Low self-esteem" },
  { label: "Mental health", id: "Mental health" },
  { label: "Miscarriage", id: "Miscarriage" },
  { label: "Money", id: "Money" },
  { label: "Narcissistic abuse", id: "Narcissistic abuse" },
  {
    label: "Narcissistic personality disorder",
    id: "Narcissistic personality disorder",
  },
  { label: "Neurodiversity", id: "Neurodiversity" },
  { label: "Non-monogamy", id: "Non-monogamy" },
  {
    label: "Obsessive compulsive disorder (OCD)",
    id: "Obsessive compulsive disorder (OCD)",
  },
  {
    label: "Obsessive-compulsive personality disorder",
    id: "Obsessive-compulsive personality disorder",
  },
  { label: "Older people's counselling", id: "Older people's counselling" },
  { label: "Panic attacks", id: "Panic attacks" },
  { label: "Paranoia", id: "Paranoia" },
  {
    label: "Paranoid personality disorder",
    id: "Paranoid personality disorder",
  },
  {
    label: "Passive-aggressive behaviour",
    id: "Passive-aggressive behaviour",
  },
  { label: "Perfectionism", id: "Perfectionism" },
  { label: "Personality disorders", id: "Personality disorders" },
  { label: "Phobias", id: "Phobias" },
  { label: "Physical abuse", id: "Physical abuse" },
  {
    label: "Post-traumatic stress disorder (PTSD)",
    id: "Post-traumatic stress disorder (PTSD)",
  },
  { label: "Postnatal depression", id: "Postnatal depression" },
  { label: "Psychosis", id: "Psychosis" },
  { label: "Race and racial identity", id: "Race and racial identity" },
  { label: "Racism", id: "Racism" },
  { label: "Redundancy", id: "Redundancy" },
  { label: "Relationship problems", id: "Relationship problems" },
  {
    label: "Schizoid personality disorder",
    id: "Schizoid personality disorder",
  },
  { label: "Schizophrenia", id: "Schizophrenia" },
  {
    label: "Schizotypal personality disorder",
    id: "Schizotypal personality disorder",
  },
  {
    label: "Seasonal affective disorder (SAD)",
    id: "Seasonal affective disorder (SAD)",
  },
  { label: "Self-harm", id: "Self-harm" },
  { label: "Separation and divorce", id: "Separation and divorce" },
  { label: "Separation anxiety", id: "Separation anxiety" },
  { label: "Sex addiction", id: "Sex addiction" },
  { label: "Sex problems", id: "Sex problems" },
  { label: "Sexual abuse", id: "Sexual abuse" },
  { label: "Sexual assault", id: "Sexual assault" },
  { label: "Smoking cessation", id: "Smoking cessation" },
  { label: "Social anxiety", id: "Social anxiety" },
  { label: "Spirituality", id: "Spirituality" },
  { label: "Stress", id: "Stress" },
  { label: "Suicidal thoughts", id: "Suicidal thoughts" },
  { label: "Tourette's syndrome", id: "Tourette's syndrome" },
  { label: "Trauma", id: "Trauma" },
  { label: "Trichotillomania", id: "Trichotillomania" },
  { label: "Work-related stress", id: "Work-related stress" },
  { label: "Young carers", id: "Young carers" },
  { label: "Young people's counselling", id: "Young people's counselling" },
];

export default placeholderOptions;
