const placeholderOptions = [
  { label: "Any", value: "Any" },
  { label: "Abortion", value: "Abortion" },
  { label: "Abuse", value: "Abuse" },
  { label: "Addiction", value: "Addiction" },
  { label: "ADHD", value: "ADHD" },
  {
    label: "Adoption counselling for adults",
    value: "Adoption counselling for adults",
  },
  {
    label: "Adoption counselling for children",
    value: "Adoption counselling for children",
  },
  { label: "Affairs and betrayals", value: "Affairs and betrayals" },
  { label: "Alcoholism", value: "Alcoholism" },
  { label: "Anger management", value: "Anger management" },
  { label: "Anorexia nervosa", value: "Anorexia nervosa" },
  {
    label: "Antisocial personality disorder",
    value: "Antisocial personality disorder",
  },
  { label: "Anxiety", value: "Anxiety" },
  { label: "ARFID", value: "ARFID" },
  { label: "Asperger's syndrome", value: "Asperger's syndrome" },
  { label: "Attachment disorder", value: "Attachment disorder" },
  {
    label: "Attachment disorder in children",
    value: "Attachment disorder in children",
  },
  { label: "Autism", value: "Autism" },
  {
    label: "Avoidant personality disorder",
    value: "Avoidant personality disorder",
  },
  { label: "Baby loss", value: "Baby loss" },
  { label: "Behaviour problems", value: "Behaviour problems" },
  { label: "Bereavement", value: "Bereavement" },
  { label: "Binge-eating disorder", value: "Binge-eating disorder" },
  { label: "Bipolar disorder", value: "Bipolar disorder" },
  { label: "Blended family", value: "Blended family" },
  { label: "Boarding school syndrome", value: "Boarding school syndrome" },
  {
    label: "Body dysmorphic disorder (BDD)",
    value: "Body dysmorphic disorder (BDD)",
  },
  {
    label: "Borderline personality disorder (BPD)",
    value: "Borderline personality disorder (BPD)",
  },
  { label: "Bulimia nervosa", value: "Bulimia nervosa" },
  { label: "Bullying", value: "Bullying" },
  { label: "Burnout", value: "Burnout" },
  { label: "Cancer", value: "Cancer" },
  { label: "Career counselling", value: "Career counselling" },
  { label: "Carer support", value: "Carer support" },
  { label: "Child counselling", value: "Child counselling" },
  { label: "Childhood bereavement", value: "Childhood bereavement" },
  { label: "Childhood bullying", value: "Childhood bullying" },
  { label: "Childless not by choice", value: "Childless not by choice" },
  {
    label: "Children’s learning difficulties",
    value: "Children’s learning difficulties",
  },
  {
    label: "Chronic fatigue syndrome/ME",
    value: "Chronic fatigue syndrome/ME",
  },
  { label: "Chronic illness", value: "Chronic illness" },
  { label: "Climate and eco-anxiety", value: "Climate and eco-anxiety" },
  { label: "Dementia", value: "Dementia" },
  {
    label: "Dependent personality disorder",
    value: "Dependent personality disorder",
  },
  { label: "Depression", value: "Depression" },
  {
    label: "Depression and anxiety in children",
    value: "Depression and anxiety in children",
  },
  { label: "Disabilities", value: "Disabilities" },
  { label: "Discrimination", value: "Discrimination" },
  { label: "Dissociation", value: "Dissociation" },
  { label: "Domestic abuse", value: "Domestic abuse" },
  { label: "Drug addiction", value: "Drug addiction" },
  { label: "Dyslexia", value: "Dyslexia" },
  { label: "Dyspraxia", value: "Dyspraxia" },
  { label: "Eating disorders", value: "Eating disorders" },
  { label: "Emotional abuse", value: "Emotional abuse" },
  { label: "Family issues", value: "Family issues" },
  { label: "Feeling sad", value: "Feeling sad" },
  { label: "Gambling", value: "Gambling" },
  { label: "Gender dysphoria", value: "Gender dysphoria" },
  {
    label: "Generalised anxiety disorder (GAD)",
    value: "Generalised anxiety disorder (GAD)",
  },
  { label: "Health anxiety", value: "Health anxiety" },
  { label: "Hearing voices", value: "Hearing voices" },
  { label: "High sensitivity", value: "High sensitivity" },
  {
    label: "Histrionic personality disorder",
    value: "Histrionic personality disorder",
  },
  { label: "HIV/AIDS", value: "HIV/AIDS" },
  { label: "Hoarding", value: "Hoarding" },
  { label: "Infertility", value: "Infertility" },
  { label: "Internet addiction", value: "Internet addiction" },
  { label: "Jealousy", value: "Jealousy" },
  { label: "Kink-aware therapy", value: "Kink-aware therapy" },
  { label: "Learning difficulties", value: "Learning difficulties" },
  { label: "Learning disabilities", value: "Learning disabilities" },
  { label: "LGBTQ+ counselling", value: "LGBTQ+ counselling" },
  { label: "Loneliness", value: "Loneliness" },
  { label: "Low self-confidence", value: "Low self-confidence" },
  { label: "Low self-esteem", value: "Low self-esteem" },
  { label: "Menopause", value: "Menopause" },
  { label: "Mental health", value: "Mental health" },
  { label: "Miscarriage", value: "Miscarriage" },
  { label: "Money", value: "Money" },
  { label: "Narcissistic abuse", value: "Narcissistic abuse" },
  {
    label: "Narcissistic personality disorder",
    value: "Narcissistic personality disorder",
  },
  { label: "Neurodiversity", value: "Neurodiversity" },
  { label: "Non-monogamy", value: "Non-monogamy" },
  {
    label: "Obsessive compulsive disorder (OCD)",
    value: "Obsessive compulsive disorder (OCD)",
  },
  {
    label: "Obsessive-compulsive personality disorder",
    value: "Obsessive-compulsive personality disorder",
  },
  { label: "Older people's counselling", value: "Older people's counselling" },
  { label: "Panic attacks", value: "Panic attacks" },
  { label: "Paranoia", value: "Paranoia" },
  {
    label: "Paranoid personality disorder",
    value: "Paranoid personality disorder",
  },
  {
    label: "Passive-aggressive behaviour",
    value: "Passive-aggressive behaviour",
  },
  { label: "Perfectionism", value: "Perfectionism" },
  { label: "Personality disorders", value: "Personality disorders" },
  { label: "Phobias", value: "Phobias" },
  { label: "Physical abuse", value: "Physical abuse" },
  {
    label: "Post-traumatic stress disorder (PTSD)",
    value: "Post-traumatic stress disorder (PTSD)",
  },
  { label: "Postnatal depression", value: "Postnatal depression" },
  { label: "Pregnancy and birth", value: "Pregnancy and birth" },
  { label: "Psychosis", value: "Psychosis" },
  { label: "Race and racial identity", value: "Race and racial identity" },
  { label: "Racism", value: "Racism" },
  { label: "Redundancy", value: "Redundancy" },
  { label: "Relationship problems", value: "Relationship problems" },
  {
    label: "Schizoid personality disorder",
    value: "Schizoid personality disorder",
  },
  { label: "Schizophrenia", value: "Schizophrenia" },
  {
    label: "Schizotypal personality disorder",
    value: "Schizotypal personality disorder",
  },
  {
    label: "Seasonal affective disorder (SAD)",
    value: "Seasonal affective disorder (SAD)",
  },
  { label: "Self-harm", value: "Self-harm" },
  { label: "Separation and divorce", value: "Separation and divorce" },
  { label: "Separation anxiety", value: "Separation anxiety" },
  { label: "Sex addiction", value: "Sex addiction" },
  { label: "Sex problems", value: "Sex problems" },
  { label: "Sexual abuse", value: "Sexual abuse" },
  { label: "Sexual assault", value: "Sexual assault" },
  { label: "Smoking", value: "Smoking" },
  { label: "Social anxiety", value: "Social anxiety" },
  { label: "Spirituality", value: "Spirituality" },
  { label: "Stress", value: "Stress" },
  { label: "Suicidal thoughts", value: "Suicidal thoughts" },
  { label: "Tourette's syndrome", value: "Tourette's syndrome" },
  { label: "Trauma", value: "Trauma" },
  { label: "Trichotillomania", value: "Trichotillomania" },
  { label: "Work-related stress", value: "Work-related stress" },
  { label: "Young carers", value: "Young carers" },
  { label: "Young people's counselling", value: "Young people's counselling" },
  ,
];

export default placeholderOptions;
