import type { Metadata } from "next";
import "./globals.css";
import "./responsive.css";
import { Roboto, Rubik } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/theme";
import CssBaseline from "@mui/material/CssBaseline";
import { Box } from "@mui/material";
import { Header } from "@/components/HeaderComponent";
import Image from "next/image";
import StickyHeader from "@/components/StickyHeader";
import Footer from "@/components/FooterComponent";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

const rubik = Rubik({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} ${roboto.variable}`}>
        <AppRouterCacheProvider>
          <CssBaseline />
          <ThemeProvider theme={theme}>
            <Box
              sx={{
                bgcolor: "background.default",
                minHeight: "100vh",
                margin: 0,
                padding: 0,
              }}
            >
              <div className="background-image-container">
                <Image
                  src="/assets/MTH - SVG transparent logo only.svg"
                  alt="background-logo"
                  fill
                  priority
                  className="background-image"
                />
              </div>
              <Box sx={{ position: "relative", zIndex: 1 }}>
                <Header />
                <StickyHeader />
                {children}
                <Footer />
              </Box>
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
