import type { Metadata } from "next";
import "./globals.css";
import "./responsive.css";
import { Roboto, Rubik } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@frontend/theme";
import CssBaseline from "@mui/material/CssBaseline";
import { Box } from "@mui/material";
import { Header } from "@frontend/_components/HeaderComponent";
import Image from "next/image";
import StickyHeader from "@frontend/_components/StickyHeader";
import Footer from "@frontend/_components/FooterComponent";
import { headers as getHeaders } from "next/headers.js";
import { getPayload } from "payload";
import config from "@/payload.config";
import AdminBar from "./_components/AdminBarComponent";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

const rubik = Rubik({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headers = await getHeaders();
  const payloadConfig = await config;
  const payload = await getPayload({ config: payloadConfig });
  const { user } = await payload.auth({ headers });

  return (
    <html lang="en">
      <body className={`${rubik.variable} ${roboto.variable}`}>
        <AppRouterCacheProvider>
          <CssBaseline />
          <ThemeProvider theme={theme}>
            <Box
              sx={{
                bgcolor: "background.default",
                minHeight: "100vh",
                margin: user ? "58px 0 0 0" : 0,
                padding: 0,
              }}
            >
              <div className="background-image-container">
                <Image
                  src="/assets/MTH - SVG transparent logo only.svg"
                  alt="background-logo"
                  fill
                  priority
                  className="background-image"
                />
              </div>
              <Box sx={{ position: "relative", zIndex: 1 }}>
                {user && <AdminBar user={user} />}
                <Header />
                <StickyHeader />
                {children}
                <Footer />
              </Box>
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
