const placeholderTherapyTypes = [
  {
    label: "Any",
    id: "Any",
  },
  {
    label: "Accelerated experiential dynamic psychotherapy (AEDP)",
    id: "Accelerated experiential dynamic psychotherapy (AEDP)",
  },
  {
    label: "Acceptance and commitment therapy (ACT)",
    id: "Acceptance and commitment therapy (ACT)",
  },
  { label: "Behavioural therapy", id: "Behavioural therapy" },
  {
    label: "Cognitive analytic therapy (CAT)",
    id: "Cognitive analytic therapy (CAT)",
  },
  {
    label: "Cognitive behavioural therapy (CBT)",
    id: "Cognitive behavioural therapy (CBT)",
  },
  {
    label: "Cognitive processing therapy (CPT)",
    id: "Cognitive processing therapy (CPT)",
  },
  {
    label: "Cognitive stimulation therapy",
    id: "Cognitive stimulation therapy",
  },
  { label: "Cognitive therapy", id: "Cognitive therapy" },
  {
    label: "Dialectical behavioural therapy (DBT)",
    id: "Dialectical behavioural therapy (DBT)",
  },
  {
    label: "Prolonged exposure therapy (PET)",
    id: "Prolonged exposure therapy (PET)",
  },
  {
    label: "Rational emotive behaviour therapy (REBT)",
    id: "Rational emotive behaviour therapy (REBT)",
  },
  { label: "Social recovery therapy", id: "Social recovery therapy" },
  { label: "Trauma-focused CBT", id: "Trauma-focused CBT" },
  { label: "Adlerian therapy", id: "Adlerian therapy" },
  { label: "Animal-assisted therapy", id: "Animal-assisted therapy" },
  { label: "Equine therapy", id: "Equine therapy" },
  { label: "Walk and talk therapy", id: "Walk and talk therapy" },
  { label: "Applied psychology", id: "Applied psychology" },
  { label: "Art therapy", id: "Art therapy" },
  { label: "Bibliotherapy", id: "Bibliotherapy" },
  { label: "Dance therapy", id: "Dance therapy" },
  { label: "Family Therapy", id: "Family Therapy" },
  { label: "Attachment-based therapy", id: "Attachment-based therapy" },
  { label: "Structural family therapy", id: "Structural family therapy" },

  { label: "Coaching", id: "Coaching" },
  { label: "Compassion-focused therapy", id: "Compassion-focused therapy" },
  { label: "Hypnotherapy", id: "Hypnotherapy" },
  { label: "Integrative counselling", id: "Integrative counselling" },
  { label: "Interpersonal therapy", id: "Interpersonal therapy" },
  { label: "Mindfulness", id: "Mindfulness" },
  { label: "Psychosexual therapy", id: "Psychosexual therapy" },
  { label: "Schema therapy", id: "Schema therapy" },
  { label: "Core process psychotherapy", id: "Core process psychotherapy" },
  { label: "Couples therapy", id: "Couples therapy" },
  {
    label: "Emotionally focused couple therapy (EFT)",
    id: "Emotionally focused couple therapy (EFT)",
  },
  {
    label: "Imago relationship therapy (IRT)",
    id: "Imago relationship therapy (IRT)",
  },
  { label: "The Gottman Method", id: "The Gottman Method" },
  {
    label: "Dynamic interpersonal therapy",
    id: "Dynamic interpersonal therapy",
  },
  { label: "Jungian therapy", id: "Jungian therapy" },
  { label: "Psychoanalysis", id: "Psychoanalysis" },
  { label: "Psychoanalytic therapy", id: "Psychoanalytic therapy" },
  { label: "Psychodynamic therapy", id: "Psychodynamic therapy" },
  { label: "Eclectic counselling", id: "Eclectic counselling" },
  { label: "EMDR", id: "EMDR" },
  { label: "Humanistic therapy", id: "Humanistic therapy" },
  { label: "Emotion-focused therapy", id: "Emotion-focused therapy" },
  { label: "Existential therapy", id: "Existential therapy" },
  { label: "Gestalt therapy", id: "Gestalt therapy" },
  { label: "Human Givens psychotherapy", id: "Human Givens psychotherapy" },
  {
    label: "Motivational interviewing (MI)",
    id: "Motivational interviewing (MI)",
  },
  { label: "Person-centred therapy", id: "Person-centred therapy" },
  { label: "Psychosynthesis", id: "Psychosynthesis" },
  { label: "Reality therapy", id: "Reality therapy" },
  {
    label: "Solution focused brief therapy",
    id: "Solution focused brief therapy",
  },
  { label: "Strength-based therapy", id: "Strength-based therapy" },
  { label: "Transactional analysis", id: "Transactional analysis" },
  { label: "Transpersonal psychology", id: "Transpersonal psychology" },
  { label: "Somatic therapy", id: "Somatic therapy" },
  {
    label: "Emotional freedom technique (EFT)",
    id: "Emotional freedom technique (EFT)",
  },
  { label: "Experiential therapy", id: "Experiential therapy" },
  {
    label: "Exposure and response prevention (ERP)",
    id: "Exposure and response prevention (ERP)",
  },
  { label: "Group therapy", id: "Group therapy" },
  { label: "Psychodrama", id: "Psychodrama" },
  { label: "Intercultural therapy", id: "Intercultural therapy" },
  {
    label: "Internal family systems therapy (IFS)",
    id: "Internal family systems therapy (IFS)",
  },
  { label: "Mentalisation-based therapy", id: "Mentalisation-based therapy" },
  { label: "Narrative therapy", id: "Narrative therapy" },
  {
    label: "Neuro-linguistic programming (NLP)",
    id: "Neuro-linguistic programming (NLP)",
  },
  { label: "Neurofeedback", id: "Neurofeedback" },
  { label: "Positive psychology", id: "Positive psychology" },
  { label: "Relational therapy", id: "Relational therapy" },
  { label: "Systemic therapy", id: "Systemic therapy" },
];

export default placeholderTherapyTypes;
